package com.demo;

/**
 * Create by Warriors Team
 * On 28/03/2021
 */

public enum Mode {
    NONE, POINT, PEN, LINE, RECTANGLE, CIRCLE, ELLIPSE, ELLIPSE_DASH, TRIANGLE, POLYGON, MOVE, ROTATE, SCALE, REFLECT, FILL_COLOR, RECTANGULAR, CYLINDER, CONE;
}
